OPENAI_API_KEY="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"
ASSISTANT_ID="asst_OvMldgyIFCHAXVN7WTkIEs3n"
REPLICATE_API_TOKEN="r8_TgczudvjXQFodTagwwDZr3tzREBrEOA3GSiwZ"